# Generated by Django 3.2.2 on 2021-05-16 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredient', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('unit_measure', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('recipe_source', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_measure', models.CharField(max_length=20, null=True)),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(db_column='ingredient', on_delete=django.db.models.deletion.CASCADE, to='weekly_planner.ingredients')),
                ('recipe_name', models.ForeignKey(db_column='recipe_name', on_delete=django.db.models.deletion.CASCADE, to='weekly_planner.recipe')),
            ],
        ),
    ]
