# Generated by Django 3.0.6 on 2020-06-03 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredient', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('unit_measure', models.CharField(choices=[('gr', 'grams'), ('ml', 'milliliters'), ('kg', 'kilograms'), ('lt', 'litre')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('recipe_source', models.CharField(choices=[('GF', 'Giallo Zafferano'), ('MY', 'Mysia')], max_length=100)),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekly_planner.Ingredients')),
                ('recipe_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekly_planner.Recipe')),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
