# Generated by Django 3.2.2 on 2021-05-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='ingredient_id',
            field=models.CharField(default='default', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe_fact',
            name='ingredient_id',
            field=models.ForeignKey(db_column='ingredient_id', default='default', on_delete=django.db.models.deletion.CASCADE, to='weekly_planner.ingredients'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe_fact',
            name='ingredient',
            field=models.CharField(max_length=50),
        ),
    ]
