# Generated by Django 3.2.2 on 2021-05-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_planner', '0002_auto_20210516_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient',
            field=models.CharField(db_column='ingredient', max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient_id',
            field=models.CharField(db_column='ingredient_id', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, db_column='timestamp'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='unit_measure',
            field=models.CharField(db_column='unit_measure', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(db_column='recipe_name', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_source',
            field=models.CharField(db_column='recipe_source', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, db_column='timestamp'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.URLField(db_column='url'),
        ),
        migrations.AlterField(
            model_name='recipe_fact',
            name='ingredient',
            field=models.CharField(db_column='ingredient', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe_fact',
            name='quantity',
            field=models.IntegerField(db_column='quantity'),
        ),
        migrations.AlterField(
            model_name='recipe_fact',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, db_column='timestamp'),
        ),
        migrations.AlterField(
            model_name='recipe_fact',
            name='unit_measure',
            field=models.CharField(db_column='unit_measure', max_length=20, null=True),
        ),
    ]
