# Generated by Django 3.0.6 on 2020-06-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_planner', '0002_auto_20200603_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='unit_measure',
            field=models.CharField(choices=[('gr', 'grams'), ('ml', 'milliliters'), ('kg', 'kilograms'), ('lt', 'litre'), (' ', 'unit')], max_length=20, null=True),
        ),
    ]
