# Generated by Django 3.0.6 on 2020-06-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_planner', '0003_auto_20200603_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_fact',
            name='ingredient',
            field=models.ForeignKey(db_column='ingredient', on_delete=django.db.models.deletion.CASCADE, to='weekly_planner.Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe_fact',
            name='recipe_name',
            field=models.ForeignKey(db_column='recipe_name', on_delete=django.db.models.deletion.CASCADE, to='weekly_planner.Recipe'),
        ),
    ]
